### ISSUE TITLE
Cannot load worlds with this mod installed

### ISSUE THREAD

**Issue by txnitxnichopper** [Keksuccino/Load-My-Resources#1]
Just throws a datapack error on load. Goes away if I remove the mod.

Log is massive and full of recipe errors that are not normally there. Had to upload to Discord as it's over 30MB. 

https://cdn.discordapp.com/attachments/438496576944472075/897002607388790804/latest.log

![image](https://user-images.githubusercontent.com/67132971/136740755-012b6c43-e106-40ab-9fdf-780ddd2b7586.png)

Mod list:

https://gist.github.com/viceversagames/fad5246e9790ccab271c4908099f1807

**Comment by Keksuccino** [comment]
Load My Resources v1.0.0-1 for MC 1.16 and 1.17 hopefully fixes this issue. If not, then there's not much I can do here and it's most probably just an incompatibility with one of your other mods. The mod now injects the pack directly into the resource pack repository and loads it exactly like the default MC pack.
