### ISSUE TITLE
Order system

### ISSUE THREAD

**Issue by JamesMinoucha** [Keksuccino/Load-My-Resources#10]
hey. In the vanilla Minecraft tab for resource packs, you can select an order, and this is nice for making a mix of packs. Do you think you can implement a system like this?

For example in config.cfg, a boolean value to activate the order system, and you will have to manually select the files.

**Comment by JamesMinoucha** [comment]
> I second that. We need resources folder to no longer act as "assets" folder, but as "resourcepacks" folder, with alphabetical load order and a config file where we can set custom load order. Sorta like Paxi mod does it, but keep resource packs hidden.

I think the mod developer is no longer active sadly :(

**Comment by Keksuccino** [comment]
I am still active, but the mod is not maintained anymore. Threre are other mods that can load resources and probably work way better than LMR anyways.
