### ISSUE TITLE
Even with the new mixin update, unable to start a new single player world.

### ISSUE THREAD

**Issue by netcore10** [Keksuccino/Load-My-Resources#2]
**Describe the bug**
Even with the mixin update, I can't create new single-player world. Safe mode does nothing.

**To Reproduce**
Steps to reproduce the behaviour:
Self-explanatory.

**Expected behavior**
To create a new single-player world.

**Screenshots**
![image](https://user-images.githubusercontent.com/181536/137492625-f6d160fd-f4ab-48b7-b4fb-374e0f9c5917.png)

**Basic Informations (please complete the following information):**
 - OS: Windows
 - Drippy Loading Screen Version: None
 - Forge/Fabric Version 36.2.8
 - Minecraft Version 1.16.5
 - Active Mods:
[modlist.txt](https://github.com/Keksuccino/Load-My-Resources/files/7353662/modlist.txt)

**Comment by Keksuccino** [comment]
[just a note for myself]

- Patchouli
- FPSReducer

**Comment by Keksuccino** [comment]
Do you have any resource packs or data packs enabled?

**Comment by Keksuccino** [comment]
Already tested mods:
![Screenshot_1](https://user-images.githubusercontent.com/35544624/137563236-908d5730-fb44-455c-9efe-4f67bc767dfd.png)

They seem to work great with LMR. I can load and create worlds without any problems.

**Comment by Keksuccino** [comment]
Was able to identify the conflicting mod, it's Refined Storage + its dependencies.
Will now try to find out **why** it's conflicting with LMR.

**Comment by netcore10** [comment]
Nice! Thank you so much for the effort.

**Comment by netcore10** [comment]
👍 thank you!
