### ISSUE TITLE
game crashes when pressing options

### ISSUE THREAD

**Issue by szunakabeats** [Keksuccino/Load-My-Resources#3]
**Describe the bug**

When im in the main menu and then click on options, the game instantly crashes.

**To Reproduce**

1. Make a 1.18 Fabric Instance
2. Install: LoadMyResources
3. Start the game and go into Options

**Expected behavior**

Seeing the options menu and make changes to something.

**Crash Log**

(file attached)
[crash-2021-12-02_10.51.49-client.txt](https://github.com/Keksuccino/Load-My-Resources/files/7640925/crash-2021-12-02_10.51.49-client.txt)

**Basic Informations:**

 - OS: Windows 11
 - LoadMyResources Version: 1.0.1
 - Fabric Version: 0.12.8
 - Minecraft Version: 1.18
 - Active Mods: none

**Comment by nick-fisch** [comment]
Same for me
[crash-2021-12-02_13.22.16-client.txt](https://github.com/Keksuccino/Load-My-Resources/files/7641777/crash-2021-12-02_13.22.16-client.txt)

**Comment by Keksuccino** [comment]
Fixed in Load My Resources v1.0.1-1! Thank you for your report!
