### ISSUE TITLE
Crashes Everytime when i open Settings 

### ISSUE THREAD

**Issue by Hatakechop3** [Keksuccino/Load-My-Resources#4]
**Describe the bug**

_Ok so I use the Fancy menu mod and whilst using that mod u need to use this mod
so when I use this mod The Game Crashed When I Open Settings Tab_

**To Reproduce**
_1. Open Minecraft
2. Click on 'Settings / Option Tab
3. Error Recreated_

**Expected behavior**
A clear and detailed description of what you expected to happen.
_I Expect it to not crash ig?_

**Crash Log**
If the bug includes a crash, please paste or link it here.
`https://pastebin.com/yeYvfMzX`

**Screenshots**
_None_

**Basic Informations (please complete the following information):**
 _- OS: [e.g. Windows] Windows 
 - Drippy Loading Screen Version [e.g. 0.2] Fancy Menu Mod
 - Forge/Fabric Version [e.g. 31.2.24] Fabric 
 - Minecraft Version [e.g. 1.15.1] 1.18
 - Active Mods [e.g. Optifine, 5zig, TooManyItems]
[All  required info in crash log as pastebin ]_

**Comment by Keksuccino** [comment]
close, because switched to Discord for convo about bug
