### ISSUE TITLE
Make pack always be the first one in the list / make it have the highest priority

### ISSUE THREAD

**Issue by ardissaps** [Keksuccino/Load-My-Resources#5]
I mean is it like the texture put on top?

**Comment by Keksuccino** [comment]
I'm actually not sure about this right now, but I think LMR resources should always be on top of all other packs. (could be wrong, need to check this)

**Comment by ardissaps** [comment]
Look like it is not on top, if i put texture pack it is overriden by default directory pack.

**Comment by ardissaps** [comment]
Would you make it always on top? Like overtwriting everything

**Comment by Keksuccino** [comment]
yeah, can do this :)

**Comment by ardissaps** [comment]
Thank you!

**Comment by Xing-C** [comment]
Has this function been implemented? I want to fix the vanilla content :D

**Comment by Keksuccino** [comment]
Will probably not add this, because it's surprisingly difficult to do without reloading resources.
Yes, it would be possible, but mods could still load packs after that one in some cases and I don't see how I could force-load it with the highest priority without a reload, sorry.

**Comment by Xing-C** [comment]
Dear author, do you know another great work, it did, but the version stagnated
Is it possible for us to learn anything here?  https://github.com/lumien231/Resource-Loader

**Comment by Xing-C** [comment]
I want to overwrite the Minecraft default package and keep it at the front. Can we implement it without considering the packages of other mods?

> Will probably not add this, because it's surprisingly difficult to do without reloading resources. Yes, it would be possible, but mods could still load packs after that one in some cases and I don't see how I could force-load it with the highest priority without a reload, sorry.
> 
> It was never made to work as an actual resource pack anyways. It's to load custom resources that aren't part of a mod or the base game already.

**Comment by Keksuccino** [comment]
I don't add half-baked things to my mods, I'm sorry.
