### ISSUE TITLE
[1.19.4] Animated Texture Issues

### ISSUE THREAD

**Issue by Parkanizor** [Keksuccino/Load-My-Resources#7]
**Describe the bug**
Hello, I'm having an issue with textures being displayed incorrectly. I'm loading my resources through `.minecraft/resources` as recommended, and most of my assets *are* being loaded correctly. Normal textures, sounds, and lang file changes are all being applied. The only problem is, all *animated* textures are being shown as their full condensed sprite sheet.

To ensure it wasn't a problem with the files themselves, I converted them to a proper resource pack and tried enabling it in-game. All animated textures worked fine as intended. I disabled it and went back to loading them via Load My Resources - they appeared bugged again.

**To Reproduce**
1. Create a new instance with the versions specified below
2. Enable the provided resource pack (textures should appear fine)
3. Disable the resource pack, and instead load the assets through `.minecraft/resources`
4. Place a sea lantern or torch (they should now have bugged textures)

**Expected behavior**
Animated textures loaded with Load My Resources should have the same outcome as being loaded via a normal resource pack.

**Screenshots**
![2023-05-26_22 22 07](https://github.com/Keksuccino/Load-My-Resources/assets/108554062/16ccb10a-3287-4031-9123-ae9b4eeb7de6)

**Basic Informations:**
 - OS: [Windows 10]
 - Load My Resources version: 1.0.4-1.19.3
 - Forge version: 45.0.64
 - Minecraft version: 1.19.4
 - Tested on a fresh instance with no other mods

**Useful Files:**
[Debug Resource Pack.zip](https://github.com/Keksuccino/Load-My-Resources/files/11580998/Debug.Resource.Pack.zip)

**Comment by Puffadillo** [comment]
I thought it'd be worth mentioning that I'm still having this issue on 1.20.1. Also, it seems that `.properties` files in minecraft/optifine/ctm aren't being loaded, either. Maybe this mod is having trouble loading anything that's not a `.png` file? Again, I loaded my assets through a simple resource pack, and with an alternatvie mod called OpenLoader, and both worked file for loading animated textures and CTM files.

**Comment by Keksuccino** [comment]
There will be no more updates for LMR. I recommend you to use other resource loader mods. They probably work way better than LMR anyways.
